---
# Inventaire FortiManager
#
# Ce fichier definit les FortiManager a gerer.
# Les variables sensibles doivent etre dans un vault.

all:
  children:
    fortimanager:
      hosts:
        fmg01:
          # Surcharge possible par host
          # ansible_host: 192.168.1.100

      vars:
        # Variables communes a tous les FMG
        ansible_network_os: fortinet.fortimanager.fortimanager
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_httpapi_port: 443
